"""empty message

Revision ID: 41ae76fb4670
Revises: 40217eaf3ac8
Create Date: 2024-11-28 02:11:55.973359

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "41ae76fb4670"
down_revision: Union[str, None] = "40217eaf3ac8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("client_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "user", "role", ["role_id"], ["id"])
    op.create_foreign_key(None, "user", "client", ["client_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="foreignkey")
    op.drop_constraint(None, "user", type_="foreignkey")
    op.drop_column("user", "client_id")
    # ### end Alembic commands ###
