"""empty message

Revision ID: 743cedaa8fef
Revises: 800b014d369f
Create Date: 2024-12-03 18:51:43.450849

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "743cedaa8fef"
down_revision: Union[str, None] = "800b014d369f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "role",
        sa.Column(
            "base_scopes", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
    )
    op.add_column(
        "role",
        sa.Column("scopes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    )
    op.add_column("role", sa.Column("client_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "role", "client", ["client_id"], ["id"])
    op.drop_column("role", "permissions")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "role",
        sa.Column(
            "permissions",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "role", type_="foreignkey")
    op.drop_column("role", "client_id")
    op.drop_column("role", "scopes")
    op.drop_column("role", "base_scopes")
    # ### end Alembic commands ###
