"""empty message

Revision ID: ca7ffb4937a0
Revises: 944895a32c29
Create Date: 2024-12-11 07:17:54.922401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca7ffb4937a0'
down_revision: Union[str, None] = '944895a32c29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('days_duration', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_strategy_association',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('portfolio', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_balance', sa.Float(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('in_process', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategy.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_strategy_association')
    op.drop_table('strategy')
    # ### end Alembic commands ###
