# name: Deploy to Server

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2

  #     - name: Log in to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_PASSWORD }}

  #     - name: Build Docker image
  #       run: |
  #         cd ./auth-service/api && docker build -t menoitami/auth_service:latest .

  #     - name: Push Docker image to Docker Hub
  #       run: |
  #         docker push menoitami/auth_service:latest

  # deploy:
  #   runs-on: ubuntu-latest
  #   # needs: build

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2

  #     - name: Set up SSH
  #       uses: webfactory/ssh-agent@v0.5.3
  #       with:
  #         ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

  #     - name: Deploy via SSH
  #       env:
  #         HOST: ${{ secrets.HOST_IP }}
  #         USER: ${{ secrets.USER_NAME }}
  #       run: |
  #         ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
  #           cd ${{ secrets.DIR_AUTH_SERVICE }}
  #           git pull
  #           docker-compose down
  #           docker-compose up --build -d
  #         EOF

  Оно работает но неважно сервер с api текущим на  https://menoitami.ru/api/docs 